# Generated by Django 5.2.8 on 2026-09-24 14:48

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0002_memberships'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('minimum_age', models.PositiveSmallIntegerField()),
                ('maximum_age', models.PositiveSmallIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.branch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
            ],
            options={
                'ordering': ['minimum_age', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('other_names', models.CharField(blank=True, max_length=200)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('recorded_age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('guardian_name', models.CharField(max_length=255)),
                ('guardian_contact', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('registration_date', models.DateField(default=datetime.date.today)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('age_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='children', to='church.agegroup')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.branch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
            ],
            options={
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('event_type', models.CharField(choices=[('sunday_service', 'Sunday service'), ('outreach', 'Outreach'), ('conference', "Children's conference"), ('camp', 'Camp'), ('training', 'Training'), ('rehearsal', 'Rehearsal'), ('special_service', 'Special service'), ('trip', 'Trip'), ('other', 'Other')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('event_date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('attendance_finalized_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendance_finalized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finalized_church_events', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.branch')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_church_events', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
            ],
            options={
                'ordering': ['-event_date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Facilitator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.branch')),
                ('default_age_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facilitators', to='church.agegroup')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='church_facilitator_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__first_name', 'user__last_name', 'user__email'],
            },
        ),
        migrations.CreateModel(
            name='ServiceSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_order', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=150)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='church.event')),
            ],
            options={
                'ordering': ['event__event_date', 'service_order'],
            },
        ),
        migrations.CreateModel(
            name='ServiceFacilitator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('lead', 'Lead'), ('assistant', 'Assistant'), ('teacher', 'Teacher'), ('volunteer', 'Volunteer'), ('other', 'Other')], default='volunteer', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='church_facilitator_assignments', to=settings.AUTH_USER_MODEL)),
                ('facilitator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_assignments', to='church.facilitator')),
                ('service_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facilitator_assignments', to='church.servicesession')),
            ],
            options={
                'ordering': ['service_session', 'role'],
            },
        ),
        migrations.CreateModel(
            name='FacilitatorAttendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attendance_status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('excused', 'Excused'), ('late', 'Late')], max_length=20)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facilitator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='church.facilitator')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_facilitator_attendance', to=settings.AUTH_USER_MODEL)),
                ('service_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facilitator_attendance', to='church.servicesession')),
            ],
            options={
                'ordering': ['-service_session__event__event_date', 'facilitator'],
            },
        ),
        migrations.CreateModel(
            name='ChildAttendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attendance_status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('excused', 'Excused'), ('late', 'Late')], max_length=20)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('age_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_snapshots', to='church.agegroup')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='church.child')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_child_attendance', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='child_attendance', to='church.event')),
                ('service_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child_attendance', to='church.servicesession')),
            ],
            options={
                'ordering': ['-event__event_date', 'child__first_name'],
            },
        ),
        migrations.AddConstraint(
            model_name='agegroup',
            constraint=models.UniqueConstraint(fields=('branch', 'name'), name='unique_church_age_group_name_branch'),
        ),
        migrations.AddConstraint(
            model_name='agegroup',
            constraint=models.CheckConstraint(condition=models.Q(('minimum_age__lte', models.F('maximum_age'))), name='church_age_group_valid_range'),
        ),
        migrations.AddIndex(
            model_name='child',
            index=models.Index(fields=['branch', 'is_active'], name='church_chil_branch__36ff27_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['branch', 'event_date'], name='church_even_branch__1687ea_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['branch', 'event_type'], name='church_even_branch__d3e17c_idx'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(condition=models.Q(('event_type', 'sunday_service'), models.Q(('status', 'cancelled'), _negated=True)), fields=('branch', 'event_date'), name='unique_active_sunday_event_branch_date'),
        ),
        migrations.AddIndex(
            model_name='facilitator',
            index=models.Index(fields=['branch', 'is_active'], name='church_faci_branch__0889ad_idx'),
        ),
        migrations.AddConstraint(
            model_name='facilitator',
            constraint=models.UniqueConstraint(fields=('branch', 'user'), name='unique_church_facilitator_branch_user'),
        ),
        migrations.AddConstraint(
            model_name='servicesession',
            constraint=models.UniqueConstraint(fields=('event', 'service_order'), name='unique_church_session_order'),
        ),
        migrations.AddConstraint(
            model_name='servicesession',
            constraint=models.UniqueConstraint(fields=('event', 'name'), name='unique_church_session_name'),
        ),
        migrations.AddConstraint(
            model_name='servicesession',
            constraint=models.CheckConstraint(condition=models.Q(('service_order__gt', 0)), name='church_session_positive_order'),
        ),
        migrations.AddConstraint(
            model_name='servicefacilitator',
            constraint=models.UniqueConstraint(fields=('service_session', 'facilitator'), name='unique_church_facilitator_assignment'),
        ),
        migrations.AddIndex(
            model_name='facilitatorattendance',
            index=models.Index(fields=['facilitator', 'service_session'], name='church_faci_facilit_7a2f9f_idx'),
        ),
        migrations.AddConstraint(
            model_name='facilitatorattendance',
            constraint=models.UniqueConstraint(fields=('service_session', 'facilitator'), name='unique_church_facilitator_attendance'),
        ),
        migrations.AddIndex(
            model_name='childattendance',
            index=models.Index(fields=['child', 'event'], name='church_chil_child_i_de6f7c_idx'),
        ),
        migrations.AddIndex(
            model_name='childattendance',
            index=models.Index(fields=['child', 'service_session'], name='church_chil_child_i_727ad6_idx'),
        ),
        migrations.AddConstraint(
            model_name='childattendance',
            constraint=models.UniqueConstraint(condition=models.Q(('service_session__isnull', True)), fields=('child', 'event'), name='unique_child_event_attendance'),
        ),
        migrations.AddConstraint(
            model_name='childattendance',
            constraint=models.UniqueConstraint(condition=models.Q(('service_session__isnull', False)), fields=('child', 'service_session'), name='unique_child_session_attendance'),
        ),
    ]
