import hashlib
import random
from datetime import date, datetime, time, timedelta

from django.contrib.auth import get_user_model
from django.core.management.base import BaseCommand, CommandError
from django.db import transaction
from django.utils import timezone

from apps.accounts.models import AccessPermission, Resource, Role
from apps.accounts.management.commands.seed_permissions import PERMISSIONS as CORE_PERMISSIONS
from apps.organization.models import Branch, BranchMembership, Organization, OrganizationMembership
from apps.church.models import (
    AgeGroup,
    AttendanceStatus,
    Child,
    ChildAttendance,
    Event,
    Facilitator,
    FacilitatorAttendance,
    ServiceFacilitator,
    ServiceSession,
)
from apps.church.services import finalize_sunday_attendance


ORGANIZATION_NAME = "Watoto Ministries"
BRANCH_NAME = "DT"
BRANCH_CODE = "DT"
DEFAULT_PASSWORD = "password123"
DEFAULT_ADMIN_EMAIL = "admin@email.com"

CHURCH_PERMISSIONS = {
    "church-dashboard": ["read"],
    "church-children": ["read"],
    "church-age-groups": ["read"],
    "church-events": ["read", "manage"],
    "church-facilitators": ["read"],
    "church-attendance": ["read", "manage"],
    "church-reports": ["read"],
}

UGANDAN_FIRST_NAMES = [
    "Achen", "Adoch", "Akello", "Amina", "Apio", "Atim", "Babirye", "Birungi",
    "Cissy", "Doreen", "Esther", "Fiona", "Flavia", "Grace", "Immaculate", "Joan",
    "Juliet", "Kellen", "Lillian", "Mariam", "Mercy", "Nabirye", "Namazzi", "Patience",
    "Peace", "Prossy", "Ritah", "Sarah", "Sharon", "Stella", "Agaba", "Akena",
    "Andrew", "Brian", "Charles", "Daniel", "Denis", "Elijah", "Emmanuel", "Geoffrey",
    "Isaac", "Ivan", "Joel", "Joshua", "Juma", "Kato", "Moses", "Mugisha",
    "Paul", "Peter", "Ronald", "Samuel", "Ssemanda", "Tendo", "Timothy", "Wasswa",
]

UGANDAN_SURNAMES = [
    "Abaho", "Aciro", "Adoch", "Agaba", "Akello", "Akumu", "Alinda", "Amanya",
    "Angwech", "Atuhaire", "Auma", "Baluku", "Bamwesigye", "Birungi", "Byaruhanga",
    "Kabuye", "Kagimu", "Kakooza", "Kalema", "Kamya", "Kato", "Kavuma", "Kisembo",
    "Kizza", "Lubega", "Lukwago", "Lwanga", "Mabirizi", "Matovu", "Mugisha",
    "Mukasa", "Musinguzi", "Nabwire", "Nakato", "Nalubega", "Namanya", "Nambasa",
    "Nansubuga", "Nanyonga", "Nsubuga", "Odongo", "Okello", "Okot", "Okwir",
    "Ssemanda", "Tumusiime", "Waiswa", "Wasswa", "Wekesa", "Yiga",
]

KAMPALA_LOCATIONS = [
    "Bakuli", "Banda", "Busega", "Bwaise", "Kansanga", "Kanyanya", "Kawempe",
    "Kibuli", "Kibuye", "Kireka", "Kisenyi", "Kololo", "Kyanja", "Lubaga",
    "Makerere", "Makindye", "Mengo", "Mpererwe", "Munyonyo", "Nakawa",
    "Namirembe", "Nansana", "Ntinda", "Rubaga", "Wandegeya",
]

FACILITATOR_NUMBER_WORDS = [
    "One", "Two", "Three", "Four", "Five", "Six",
    "Seven", "Eight", "Nine", "Ten", "Eleven", "Twelve",
]

SESSION_DEFINITIONS = [
    ("Morning Service", time(8, 0), time(9, 30)),
    ("10am Service", time(10, 0), time(11, 30)),
    ("Midday Service", time(12, 0), time(13, 30)),
    ("Afternoon Service", time(15, 0), time(16, 30)),
]


def stable_fraction(seed, *parts):
    payload = ":".join([str(seed), *(str(part) for part in parts)]).encode()
    return int.from_bytes(hashlib.sha256(payload).digest()[:8], "big") / 2**64


def weighted_status(value, weights):
    total = 0
    for status_value, weight in weights:
        total += weight
        if value < total:
            return status_value
    return weights[-1][0]


def shift_year(value, years):
    try:
        return value.replace(year=value.year + years)
    except ValueError:
        return value.replace(year=value.year + years, day=28)


def date_for_age(age, reference_date, rng):
    first = shift_year(reference_date, -(age + 1)) + timedelta(days=1)
    last = shift_year(reference_date, -age)
    return first + timedelta(days=rng.randrange((last - first).days + 1))


def elapsed_sundays(year, through_date):
    cursor = date(year, 1, 1)
    cursor += timedelta(days=(6 - cursor.weekday()) % 7)
    last = min(through_date, date(year, 12, 31))
    while cursor <= last:
        yield cursor
        cursor += timedelta(days=7)


def aware_at(day, clock, minute_offset=0):
    value = datetime.combine(day, clock) + timedelta(minutes=minute_offset)
    return timezone.make_aware(value, timezone.get_current_timezone())


class Command(BaseCommand):
    help = "Create deterministic development/demo data for Watoto Ministries DownTown."

    def add_arguments(self, parser):
        parser.add_argument("--children-per-group", type=int, default=45)
        parser.add_argument("--year", type=int, default=timezone.localdate().year)
        parser.add_argument("--through-date", default=timezone.localdate().isoformat(), help="Inclusive YYYY-MM-DD limit; future Sundays are not generated by default.")
        parser.add_argument("--password", default=DEFAULT_PASSWORD)
        parser.add_argument("--admin-email", default=DEFAULT_ADMIN_EMAIL)
        parser.add_argument("--admin-password", default=DEFAULT_PASSWORD)
        parser.add_argument("--seed", type=int, default=2026)

    def handle(self, *args, **options):
        children_per_group = options["children_per_group"]
        if not 40 <= children_per_group <= 50:
            raise CommandError("--children-per-group must be between 40 and 50.")
        try:
            through_date = date.fromisoformat(options["through_date"])
        except ValueError as exc:
            raise CommandError("--through-date must use YYYY-MM-DD format.") from exc
        through_date = min(through_date, timezone.localdate())
        if options["year"] < 2000 or options["year"] > 2100:
            raise CommandError("--year must be between 2000 and 2100.")

        self.stdout.write(self.style.WARNING("Creating DEVELOPMENT/DEMO sample data. Do not use the shared password in production."))
        with transaction.atomic():
            organization, branch = self._organization_and_branch()
            self._ensure_permission_catalog()
            age_groups = self._age_groups(organization, branch)
            administrator = self._administrator(
                organization, branch, options["admin_email"], options["admin_password"]
            )
            role = self._facilitator_role(organization)
            facilitators = self._facilitators(organization, branch, age_groups, role, options["password"])
            children = self._children(
                organization, branch, age_groups, children_per_group,
                options["seed"], options["year"],
            )
            counts = self._sundays(
                organization, branch, children, facilitators,
                options["year"], through_date, options["seed"],
            )

        self.stdout.write(self.style.SUCCESS(
            f"Watoto sample data ready: {len(children)} children, {len(facilitators)} facilitators, "
            f"{counts['events']} Sundays, {counts['sessions']} sessions, "
            f"{counts['child_attendance']} child attendance records and "
            f"{counts['facilitator_attendance']} facilitator attendance records."
        ))
        self.stdout.write(
            f"Administrator login: {administrator.email} / {options['admin_password']} "
            "(development/demo only)"
        )
        self.stdout.write(f"Facilitator login password: {options['password']} (development/demo only)")

    def _ensure_permission_catalog(self):
        """Make the demo administrator useful even on a fresh database."""
        permission_map = {**CORE_PERMISSIONS}
        for resource_code, actions in CHURCH_PERMISSIONS.items():
            permission_map[resource_code] = sorted(
                set(permission_map.get(resource_code, [])) | set(actions)
            )
        # Management permissions are intentionally absent from the facilitator
        # map but must exist for the administrator role.
        for resource_code in ("church-children", "church-age-groups", "church-facilitators"):
            permission_map[resource_code] = sorted(
                set(permission_map.get(resource_code, [])) | {"read", "manage"}
            )
        for resource_code, actions in permission_map.items():
            resource, _ = Resource.objects.update_or_create(
                code=resource_code,
                defaults={"name": resource_code.replace("-", " ").title(), "is_active": True},
            )
            for action in actions:
                AccessPermission.objects.update_or_create(
                    resource=resource,
                    action=action,
                    defaults={"codename": f"{resource_code}.{action}", "is_active": True},
                )

    def _administrator(self, organization, branch, email, password):
        User = get_user_model()
        role, _ = Role.objects.update_or_create(
            organization=organization,
            slug="administrator",
            defaults={
                "name": "Administrator",
                "description": "Full Watoto Ministries administration access.",
                "is_active": True,
            },
        )
        role.permissions.set(AccessPermission.objects.filter(is_active=True))
        user, _ = User.objects.get_or_create(email=email.lower())
        user.email = email.lower()
        user.first_name = "Admin"
        user.last_name = "Administrator"
        user.phone_number = "+256700000001"
        user.is_active = True
        user.set_password(password)
        user.save()
        OrganizationMembership.objects.update_or_create(
            organization=organization,
            user=user,
            defaults={"role": role, "is_active": True},
        )
        BranchMembership.objects.update_or_create(
            branch=branch,
            user=user,
            defaults={"is_active": True},
        )
        return user

    def _organization_and_branch(self):
        organization, _ = Organization.objects.get_or_create(
            name=ORGANIZATION_NAME,
            defaults={"slug": "watoto-ministries", "description": "Sample Children's Church data."},
        )
        branch, _ = Branch.objects.update_or_create(
            organization=organization,
            code=BRANCH_CODE,
            defaults={"name": BRANCH_NAME, "city": "Kampala", "country": "Uganda", "is_active": True},
        )
        return organization, branch

    def _age_groups(self, organization, branch):
        groups = []
        for age in range(9, 14):
            group, _ = AgeGroup.objects.update_or_create(
                branch=branch,
                name=f"Age {age}",
                defaults={"organization": organization, "minimum_age": age, "maximum_age": age, "is_active": True},
            )
            groups.append(group)
        return groups

    def _facilitator_role(self, organization):
        permissions = []
        for resource_code, actions in CHURCH_PERMISSIONS.items():
            resource, _ = Resource.objects.update_or_create(
                code=resource_code,
                defaults={"name": resource_code.replace("-", " ").title(), "is_active": True},
            )
            for action in actions:
                permission, _ = AccessPermission.objects.update_or_create(
                    resource=resource,
                    action=action,
                    defaults={"codename": f"{resource_code}.{action}", "is_active": True},
                )
                permissions.append(permission)
        role, _ = Role.objects.update_or_create(
            organization=organization,
            slug="facilitator",
            defaults={"name": "Facilitator", "description": "Children's Church facilitator", "is_active": True},
        )
        # Preserve any additional permissions already granted to an existing
        # organization role while ensuring the demo facilitators can operate.
        role.permissions.add(*permissions)
        return role

    def _facilitators(self, organization, branch, age_groups, role, password):
        User = get_user_model()
        facilitators = []
        for index, word in enumerate(FACILITATOR_NUMBER_WORDS, 1):
            email = f"facilitator{index}@email.com"
            user = User.objects.filter(email=email).first()
            if user is None:
                user = User(email=email)
            user.email = email
            user.first_name = "Facilitator"
            user.last_name = word
            user.phone_number = f"+256780{index:06d}"
            user.is_active = True
            user.set_password(password)
            user.save()
            OrganizationMembership.objects.update_or_create(
                organization=organization,
                user=user,
                defaults={"role": role, "is_active": True},
            )
            BranchMembership.objects.update_or_create(
                branch=branch,
                user=user,
                defaults={"is_active": True},
            )
            facilitator, _ = Facilitator.objects.update_or_create(
                branch=branch,
                user=user,
                defaults={
                    "organization": organization,
                    "default_age_group": age_groups[(index - 1) % len(age_groups)],
                    "is_active": True,
                    "notes": "Generated Watoto Ministries demo facilitator.",
                },
            )
            facilitators.append(facilitator)
        return facilitators

    def _children(self, organization, branch, age_groups, per_group, seed, year):
        reference_date = timezone.localdate()
        rng = random.Random(seed)
        children = []
        global_index = 0
        for group in age_groups:
            for group_index in range(per_group):
                global_index += 1
                first_name = UGANDAN_FIRST_NAMES[(global_index * 7 + group_index) % len(UGANDAN_FIRST_NAMES)]
                last_name = UGANDAN_SURNAMES[(global_index * 11 + group.minimum_age) % len(UGANDAN_SURNAMES)]
                guardian_first = UGANDAN_FIRST_NAMES[(global_index * 13) % len(UGANDAN_FIRST_NAMES)]
                guardian_last = UGANDAN_SURNAMES[(global_index * 17) % len(UGANDAN_SURNAMES)]
                contact = f"+256700{global_index:06d}"
                child, _ = Child.objects.update_or_create(
                    branch=branch,
                    guardian_contact=contact,
                    defaults={
                        "organization": organization,
                        "first_name": first_name,
                        "last_name": last_name,
                        "other_names": "",
                        "date_of_birth": date_for_age(group.minimum_age, reference_date, rng),
                        "age_group": group,
                        "guardian_name": f"{guardian_first} {guardian_last}",
                        "location": KAMPALA_LOCATIONS[(global_index - 1) % len(KAMPALA_LOCATIONS)],
                        "registration_date": date(year, 1, 1),
                        "is_active": True,
                    },
                )
                children.append(child)
        return children

    def _sundays(self, organization, branch, children, facilitators, year, through_date, seed):
        actor = facilitators[0].user
        sunday_dates = list(elapsed_sundays(year, through_date))
        for sunday in sunday_dates:
            event, _ = Event.objects.update_or_create(
                branch=branch,
                event_date=sunday,
                event_type=Event.Type.SUNDAY_SERVICE,
                defaults={
                    "organization": organization,
                    "name": f"Sunday Service, {sunday:%d %B %Y}",
                    "description": "Generated Watoto Ministries demo Sunday service.",
                    "location": BRANCH_NAME,
                    "status": Event.Status.COMPLETED,
                    "created_by": actor,
                },
            )
            sessions = []
            for order, (name, starts, ends) in enumerate(SESSION_DEFINITIONS, 1):
                session, _ = ServiceSession.objects.update_or_create(
                    event=event,
                    service_order=order,
                    defaults={
                        "name": name, "start_time": starts, "end_time": ends,
                        "location": BRANCH_NAME, "status": Event.Status.COMPLETED,
                    },
                )
                sessions.append(session)
                for facilitator in facilitators[(order - 1) * 3:order * 3]:
                    ServiceFacilitator.objects.update_or_create(
                        service_session=session,
                        facilitator=facilitator,
                        defaults={
                            "role": ServiceFacilitator.Role.LEAD if facilitator == facilitators[(order - 1) * 3] else ServiceFacilitator.Role.TEACHER,
                            "assigned_by": actor,
                        },
                    )
            self._child_attendance(event, sessions, children, actor, seed)
            self._facilitator_attendance(event, sessions, facilitators, actor, seed)
            finalize_sunday_attendance(event, actor)
            event.attendance_finalized_at = aware_at(sunday, time(17, 0))
            event.attendance_finalized_by = actor
            event.status = Event.Status.COMPLETED
            event.save(update_fields=["attendance_finalized_at", "attendance_finalized_by", "status", "updated_at"])

        return {
            "events": Event.objects.filter(branch=branch, event_type=Event.Type.SUNDAY_SERVICE, event_date__in=sunday_dates).count(),
            "sessions": ServiceSession.objects.filter(event__branch=branch, event__event_date__in=sunday_dates).count(),
            "child_attendance": ChildAttendance.objects.filter(event__branch=branch, event__event_date__in=sunday_dates).count(),
            "facilitator_attendance": FacilitatorAttendance.objects.filter(service_session__event__branch=branch, service_session__event__event_date__in=sunday_dates).count(),
        }

    def _child_attendance(self, event, sessions, children, actor, seed):
        existing = {
            (record.child_id, record.service_session_id): record
            for record in ChildAttendance.objects.filter(event=event, service_session__isnull=False)
        }
        creates = []
        updates = []
        for index, child in enumerate(children):
            value = stable_fraction(seed, "child", event.event_date, child.guardian_contact)
            status_value = weighted_status(value, [
                (AttendanceStatus.PRESENT, .82), (AttendanceStatus.LATE, .05),
                (AttendanceStatus.EXCUSED, .04), (AttendanceStatus.ABSENT, .09),
            ])
            if status_value == AttendanceStatus.ABSENT:
                continue
            session = sessions[index % len(sessions)]
            minute_offset = int(stable_fraction(seed, "checkin", event.event_date, child.guardian_contact) * 12)
            if status_value == AttendanceStatus.LATE:
                minute_offset += 15
            checked_in_at = aware_at(event.event_date, session.start_time, minute_offset) if status_value in [AttendanceStatus.PRESENT, AttendanceStatus.LATE] else None
            record = existing.get((child.id, session.id))
            if record:
                record.age_group = child.age_group
                record.attendance_status = status_value
                record.checked_in_at = checked_in_at
                record.recorded_by = actor
                record.notes = "Generated Watoto Ministries demo attendance."
                updates.append(record)
            else:
                creates.append(ChildAttendance(
                    child=child, event=event, service_session=session, age_group=child.age_group,
                    attendance_status=status_value, checked_in_at=checked_in_at,
                    recorded_by=actor, notes="Generated Watoto Ministries demo attendance.",
                ))
        ChildAttendance.objects.bulk_create(creates)
        if updates:
            ChildAttendance.objects.bulk_update(updates, ["age_group", "attendance_status", "checked_in_at", "recorded_by", "notes", "updated_at"])

    def _facilitator_attendance(self, event, sessions, facilitators, actor, seed):
        existing = {
            (record.service_session_id, record.facilitator_id): record
            for record in FacilitatorAttendance.objects.filter(service_session__event=event)
        }
        creates = []
        updates = []
        for session_index, session in enumerate(sessions):
            for facilitator in facilitators[session_index * 3:(session_index + 1) * 3]:
                value = stable_fraction(seed, "facilitator", event.event_date, facilitator.user.email)
                status_value = weighted_status(value, [
                    (AttendanceStatus.PRESENT, .90), (AttendanceStatus.LATE, .05),
                    (AttendanceStatus.EXCUSED, .03), (AttendanceStatus.ABSENT, .02),
                ])
                minute_offset = int(stable_fraction(seed, "facilitator-checkin", event.event_date, facilitator.user.email) * 10)
                if status_value == AttendanceStatus.LATE:
                    minute_offset += 15
                checked_in_at = aware_at(event.event_date, session.start_time, minute_offset) if status_value in [AttendanceStatus.PRESENT, AttendanceStatus.LATE] else None
                record = existing.get((session.id, facilitator.id))
                if record:
                    record.attendance_status = status_value
                    record.checked_in_at = checked_in_at
                    record.recorded_by = actor
                    record.notes = "Generated Watoto Ministries demo facilitator attendance."
                    updates.append(record)
                else:
                    creates.append(FacilitatorAttendance(
                        service_session=session, facilitator=facilitator,
                        attendance_status=status_value, checked_in_at=checked_in_at,
                        recorded_by=actor, notes="Generated Watoto Ministries demo facilitator attendance.",
                    ))
        FacilitatorAttendance.objects.bulk_create(creates)
        if updates:
            FacilitatorAttendance.objects.bulk_update(updates, ["attendance_status", "checked_in_at", "recorded_by", "notes", "updated_at"])
